workflows:
  android-release:
    name: Build Android App
    instance_type: linux

    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/**/*.apk